### PR TITLE
Welcome screen (WIP)

### PR DESCRIPTION
**Pull request by dimaninc**

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
@ZNick1982 can you try to salvage this one?

**Comment by ZNick1982** [comment]
Sure! Will start today evening.

**Comment by dmitry-mukhin** [comment]
@ZNick1982 let's discuss this first though.

**Comment by ZNick1982** [comment]
Ok, I will message you when I analyze commits.

**Comment by ZNick1982** [comment]
@dmitry-mukhin I did analyze commits. Wrote you on Slack.

**Pull request closed without merging**
